### ISSUE TITLE
Replicating README.md example

### ISSUE THREAD

**Issue by michafi** [bcjaeger/r2glmm#12]
Hello, 

I've been problems replicating your example. The output looks different:

```
> (r2nsj = r2beta(mer1, method = 'nsj', partial = TRUE))
```

gives me:
```
              Effect   Rsq upper.CL lower.CL
1              Model 0.410    0.551    0.305
4           bs(age)3 0.231    0.369    0.111
5          SexFemale 0.032    0.126    0.000
3           bs(age)2 0.024    0.111    0.000
8 bs(age)3:SexFemale 0.016    0.095    0.000
7 bs(age)2:SexFemale 0.002    0.056    0.000
6 bs(age)1:SexFemale 0.001    0.051    0.000
2           bs(age)1 0.000    0.046    0.000
```
but not the desired:
```
#>        Effect   Rsq upper.CL lower.CL
#> 1       Model 0.410    0.551    0.305
#> 2     bs(age) 0.263    0.409    0.149
#> 3         Sex 0.032    0.126    0.000
#> 4 bs(age):Sex 0.024    0.134    0.005
```
I think this might be related to the R version (4.0.3) I'm using right now, because it used to work before updating.

Let me know if you need any further information!

Thanks in advance for your help!

Best,
Micha

**Comment by bcjaeger** [comment]
Hello! Thank you for your question. I think you will get the same results as the readme if you download the developer version of the r2glmm package.

**Comment by bcjaeger** [comment]
i.e., try running `remotes::install_github('bcjaeger/r2glmm')` in a fresh R session.

**Comment by michafi** [comment]
It works now! Thanks a lot for your fast support!
