### ISSUE TITLE
error in r2beta function when using covariates with missing data and method='kr'

### ISSUE THREAD

**Issue by Gscorreia89** [bcjaeger/r2glmm#6]
Hi,

Thank you very much for the r2glmm package, a useful addition to the R linear mixed modeling toolkit.

I came across  a small issue when using it in some data, which I managed to sort out, but since the error message was not clear I am sharing it here anyway, as it might be useful to add some checks in the function and report a clear user message or warn the user and apply the methods to the complete cases. 

Assuming an lme4 model with 2 or more fixed effects, such as:
model <- lmer(y ~ fxf + fxf2 + (1|ind), data=data_with_missing_values),

When calling r2beta(model, method='kr') on a model where the data.frame passed to 'data' contains missing values for the covariates (fxf or fxf2 in the example) I get the following error (straight from the underlying pbkrtest functions):
```
Error in cbind(Xlarge, Xsmall): number of rows of matrices must match (see arg 2)
Traceback:

1. r2beta(rsmodel, method = "kr")
2. r2beta.lmerMod(rsmodel, method = "kr")
3. pbkrtest::KRmodcomp(model, stats::update(model, null_model))
4. KRmodcomp.lmerMod(model, stats::update(model, null_model))
5. KRmodcomp_init(largeModel, smallModel, matrixOK = TRUE)
6. KRmodcomp_init.lmerMod(largeModel, smallModel, matrixOK = TRUE)
7. rankMatrix(cbind(Xlarge, Xsmall))
8. stopifnot(length(d <- dim(x)) == 2)
9. cbind(Xlarge, Xsmall)

```
The error can be easily prevented by filtering the data with complete.cases before fitting the lme4 model, and it does not occur with the 'nsj' and 'sgv' methods.

Here is a code snippet to reproduce the issue with some simulated data:
```
library(lme4)
library(r2glmm)

x <- rnorm(1000)
z_dummy <- rep(seq(1, 10))
z_draw <- rnorm(10)

data <- x + rep(z_draw, 100)

fxf <- rep(1, 1000)
fxf[500:length(fxf)] <- 2

fxf2 <- sample.int(2, 1000, replace=TRUE)

complete_data <- data.frame(y=data, fxf=fxf, fxf2=fxf2, ind=z_dummy)
fxf2[200] <- NA
data_with_missing <- data.frame(y=data, fxf=fxf, fxf2=fxf2, ind=z_dummy)

ok_model <- lmer(y ~ fxf + fxf2 + (1|ind), data=complete_data)
failing_model <-  lmer(y ~ fxf + fxf2 + (1|ind), data=data_with_missing)

r2beta(ok_model, method='kr')
r2beta(failing_model, method='kr')
```

Best Regards,
Gonçalo

**Comment by bcjaeger** [comment]
Thanks! I will get this fixed in the next update, and I really appreciate your thorough example.

**Comment by bcjaeger** [comment]
Dev version has a fix implemented now.
